version: '3'

services:
  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    #    command: yarn start:dev
    # networks:
    #   - app-network
    volumes:
      - .:/app/
      - /app/node_modules

    container_name: nest-app
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
      #- /home/postgres-data:/var/lib/postgresql/data
      # networks:
      #   - app-network

volumes:
  postgres-db:
    external: false

#networks:
#  app-networks:
#    driver: bridge
